import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { withAuthenticator } from '@aws-amplify/ui-react';

function Home({ signOut, user }) {
  console.log(user);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <div className='text-4xl font-bold text-center'>
          Hello {user.attributes.name}
        </div>
        <button onClick={() => signOut()}>
          <div className='py-3 px-6 bg-gray-800 text-white'>Sign Out</div>
        </button>
        <img src={user.attributes.picture} alt={user.attributes.name} />
      </main>
    </>
  );
}

export default withAuthenticator(Home);
